### ISSUE TITLE
linter throws error if Preflow, PostFlow tags are missing in Endpoint configuration

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigeecs/bundle-linter#10]
1) If `<PreFlow/>` or `<PostFlow/>` tag is missing in the Proxy or Target end point configurations, the script throws an exception. Would be nice if its handled and it throws error or warnings

```
/Users/testUser/GitHub/test-ci/src/package/Endpoint.js:48
    debug("preflow summary: " + JSON.stringify(this.preFlow.summarize()));
                                                           ^

TypeError: Cannot read property 'summarize' of undefined
    at Endpoint.getPreFlow (/Users/testUser/GitHub/test-ci/src/package/Endpoint.js:48:60)
    at Endpoint.onConditions (/Users/testUser/GitHub/test-ci/src/package/Endpoint.js:150:10)
    at /Users/testUser/GitHub/test-ci/src/package/Bundle.js:136:87
    at Array.forEach (native)
    at Bundle.onConditions (/Users/testUser/GitHub/test-ci/src/package/Bundle.js:136:60)
    at /Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:59:46
    at Array.forEach (native)
    at Object.lint (/Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:53:40)
    at Object.<anonymous> (/Users/testUser/GitHub/test-ci/src/sample.js:11:4)
    at Module._compile (module.js:571:32)
```

and

```
/Users/testUser/GitHub/test-ci/src/package/Endpoint.js:62
    debug("post flow summary: " + JSON.stringify(this.postFlow.summarize()));
                                                              ^

TypeError: Cannot read property 'summarize' of undefined
    at Endpoint.getPostFlow (/Users/testUser/GitHub/test-ci/src/package/Endpoint.js:62:63)
    at Endpoint.onConditions (/Users/testUser/GitHub/test-ci/src/package/Endpoint.js:152:10)
    at /Users/testUser/GitHub/test-ci/src/package/Bundle.js:135:85
    at Array.forEach (native)
    at Bundle.onConditions (/Users/testUser/GitHub/test-ci/src/package/Bundle.js:135:58)
    at /Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:59:46
    at Array.forEach (native)
    at Object.lint (/Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:53:40)
    at Object.<anonymous> (/Users/testUser/GitHub/test-ci/src/sample.js:11:4)
    at Module._compile (module.js:571:32)
```

2) If a PreFlow or PostFlow exists with just `Request` **or** `Response` policies, the script throws and error looking for the other. For example, if Request is present, it looks for Response and the vice versa

```xml
<PreFlow>
    <Request>
        <Step>
            <Name>AssignMessage.CopyRequest</Name>
        </Step>
    </Request>
</PreFlow>
```

Error:
```
/Users/testUser/GitHub/test-ci/src/package/plugins/unusedVariables.js:70
            evaluateSteps(target.getPreFlow().getFlowResponse().getSteps(), localSymtab);
                                                               ^

TypeError: Cannot read property 'getSteps' of undefined
    at /Users/testUser/GitHub/test-ci/src/package/plugins/unusedVariables.js:70:64
    at Array.forEach (native)
    at /Users/testUser/GitHub/test-ci/src/package/plugins/unusedVariables.js:58:37
    at Array.forEach (native)
    at Object.onBundle (/Users/testUser/GitHub/test-ci/src/package/plugins/unusedVariables.js:45:32)
    at /Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:57:43
    at Array.forEach (native)
    at Object.lint (/Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:53:40)
    at Object.<anonymous> (/Users/testUser/GitHub/test-ci/src/sample.js:11:4)
    at Module._compile (module.js:571:32)
```

3) If PreFlow or PostFlow empty tag is provided it looks for
```xml
<PostFlow>
    <Request/>
    <Response/>
</PostFlow>
```

**Comment by davidwallen** [comment]
Reviewing. Good catch!

**Comment by davidwallen** [comment]
Fixed - though significant testing needs to be done on the unusedVariable plugin.
