### ISSUE TITLE
npm install using npm 5.6.0 and node v8.9.4 fails

### ISSUE THREAD

**Issue by kurtkanaskie** [apigeecs/bundle-linter#105]
$ npm install

> v8-debug@1.0.1 preinstall /Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug
> node -e 'process.exit(0)'

> v8-debug@1.0.1 install /Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64"
gyp ERR! cwd /Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/kurtkanaskie/work/customers/exco/pingstatus-v1/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN pingstatus@1.0.0 No repository field.
npm WARN pingstatus@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kurtkanaskie/.npm/_logs/2018-02-26T20_45_37_262Z-debug.log

**Comment by kurtkanaskie** [comment]
Community question here: https://community.apigee.com/questions/57848/static-code-analysisapigeelint-node-version-depend.html
