### ISSUE TITLE
Unrecognized token error

### ISSUE THREAD

**Issue by EddyVos** [apigeecs/bundle-linter#106]
Hi,

I'm testing the linter on my current project.
In this project I have the following step:

`            <Step>
                <Name>JS-ValidateClientCN</Name>
                <Condition>{environment.name="sandbox"} or {environment.name="prod"}</Condition>
            </Step>`

Running the Linter gives me this error:

`PS C:\Workspaces\bundle-linter-master> node .\cli.js -s C:\bitbucket_folders\prx_mortgages-t-and-t\apiproxy -f html.js >testme2.html
Error: Unrecognized token "}" on position 2.
    at unrecognizedToken (C:\Workspaces\bundle-linter-master\lib\package\TruthTable.js:406:11)
    at TruthTable.getTokens (C:\Workspaces\bundle-linter-master\lib\package\TruthTable.js:535:13)
    at TruthTable.getAST (C:\Workspaces\bundle-linter-master\lib\package\TruthTable.js:734:32)
    at onCondition (C:\Workspaces\bundle-linter-master\lib\package\plugins\checkConditionComplexity.js:14:29)
    at C:\Workspaces\bundle-linter-master\lib\package\Step.js:114:11
    at C:\Workspaces\bundle-linter-master\node_modules\async\dist\async.js:3866:24
    at eachOfArrayLike (C:\Workspaces\bundle-linter-master\node_modules\async\dist\async.js:1055:9)
    at eachOf (C:\Workspaces\bundle-linter-master\node_modules\async\dist\async.js:1103:5)
    at _parallel (C:\Workspaces\bundle-linter-master\node_modules\async\dist\async.js:3865:5)
    at Object.parallelLimit [as parallel] (C:\LogFiles\Workspaces\bundle-linter-master\node_modules\async\dist\async.js:3948:5)
{environment.name="sandbox"} or {environment.name="prod"}`

**Comment by ssvaidyanathan** [comment]
Hi @EddyVos 
Can you please change the condition to 
```xml
<Step> 
    <Name>JS-ValidateClientCN</Name>
    <Condition>(environment.name="sandbox") or (environment.name="prod"})</Condition>
</Step>
```
Usage of `{}` is not permitted for Conditions

**Comment by davidwallen** [comment]
A new linter rule perhaps?

**Comment by EddyVos** [comment]
Hi @ssvaidyanathan ,

Will change this but maybe, like @davidwallen also suggest, is a new linter rule better then exiting with an exception?

**Comment by apetrosian** [comment]
@davidwallen I've created new rule description here https://github.com/apigeecs/bundle-linter/issues/107

@EddyVos thanks for your feedback!

**Comment by davidwallen** [comment]
Closing this ticket and picking up #107
