### ISSUE TITLE
linter throws error for empty Condition

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigeecs/bundle-linter#11]
The script throws error if Condition is empty

```xml
<Flow name="flow1">
    <Condition/>
</Flow>
```
or
```xml
<Condition></Condition>
```

The error trace:
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at interpret (/Users/testUser/GitHub/bundle-linter/src/package/Condition.js:40:22)
    at _evaluate (/Users/testUser/GitHub/bundle-linter/src/package/Condition.js:124:18)
    at process (/Users/testUser/GitHub/bundle-linter/src/package/Condition.js:139:29)
    at Condition.getAST (/Users/testUser/GitHub/bundle-linter/src/package/Condition.js:520:15)
    at Condition.getTruthTable (/Users/testUser/GitHub/bundle-linter/src/package/Condition.js:153:40)
    at onCondition (/Users/testUser/GitHub/bundle-linter/src/package/plugins/checkConditionTruth.js:7:32)
    at Flow.onConditions (/Users/testUser/GitHub/bundle-linter/src/package/Flow.js:81:28)
    at /Users/testUser/GitHub/bundle-linter/src/package/Endpoint.js:151:67
    at Array.forEach (native)
```

**Comment by davidwallen** [comment]
Fixed
