### ISSUE TITLE
linter throws error if policy does not have DisplayName

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigeecs/bundle-linter#12]
If the policy does not have `<DisplayName>` tag, it throws an error instead of throwing a warning that it is good to have

For example
```xml
<AssignMessage name="AssignMessage.CopyRequest">
	<AssignTo createNew="true" type="request">flow.apigee.originalRequest</AssignTo>
	<!-- Assign Message -->
	<Copy source="request">
		<Payload>true</Payload>
	</Copy>
</AssignMessage>
```

Error:
```
/Users/testUser/GitHub/test-ci/src/package/Policy.js:27
        this.displayName = doc[0].childNodes[0].nodeValue;
                                 ^

TypeError: Cannot read property 'childNodes' of undefined
    at Policy.getDisplayName (/Users/testUser/GitHub/test-ci/src/package/Policy.js:27:34)
    at onPolicy (/Users/testUser/GitHub/test-ci/src/package/plugins/checkFileName.js:9:26)
    at Array.forEach (native)
    at Bundle.onPolicies (/Users/testUser/GitHub/test-ci/src/package/Bundle.js:124:23)
    at /Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:63:43
    at Array.forEach (native)
    at Object.lint (/Users/testUser/GitHub/test-ci/src/package/bundleLinter.js:53:40)
    at Object.<anonymous> (/Users/testUser/GitHub/test-ci/src/sample.js:11:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by davidwallen** [comment]
Fixed
